spring:
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
   datasource:
      url: jdbc:mysql://localhost:3306/api_gateway
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
   level:
      org:
         springframework:
            web: INFO
server:
   port: 8080
   ssl:
      key-store: classpath:tls/keystore.jks
      key-store-password: changeit
      trust-store: classpath:tls/truststore.jks
      trust-store-password: changeit
      client-auth: need
auth:
   in-memory: false
   users:
      -
         name: bob
         roles:
            - INSERT
      -
         name: APP1
         roles:
            - ADMIN
      -
         name: APP2
         roles:
            - INSERT
            - READ
      -
         name: APP3
         roles:
            - ADMIN
jwt:
   contains-role: true